borgmatic-collective/docker-borgmatic

Dockerfile
README.md

If tzdata is available in the image the local time can be used by setting
the TZ environment variable.
Resolves #4.

Add tzdata

---

Dockerfile
crontab.txt

Not sure whether you like both commits or just the llfuse one. Let me know if it's the latter.

Add llfuse support & Fix issue with config file path

---

.env.template
.gitignore
README.md
docker-compose.restore.yml
docker-compose.yml

Added a docker-compose override file for backup restore, removed comments for backup restore from docker-compose.yml and added documentation to README

Updated docker-compose files

---

Dockerfile

added fuse to enable mounting backups

---

base/Dockerfile
base/README.md
base/docker-compose.yml
msmtp/docker-compose.yml
ntfy/docker-compose.yml

@witten - I've created this PR with regards to your issue #55 - More than happy to merge just wanted to work this way (branches merging into master) from now on.

🎄 Removed .borgmatic volume mapping

---

base/Dockerfile
msmtp/Dockerfile
ntfy/Dockerfile

Testing a build locally before merging

Borg v1.1.15

---

base/Dockerfile
msmtp/Dockerfile
ntfy/Dockerfile

- fix maintainer labels
- upgrade borg and borgmatic to latest versions

Upgrade borg and borgmatic to latest versions

---

base/README.md

README: Add example for controlling other containers from borgmatic hooks

---

.github/workflows/build_latest.yml
.github/workflows/build_new_version.yml

As discussed in https://github.com/b3vis/docker-borgmatic/issues/54.
To make this work you have to add DOCKER_USERNAME and DOCKER_PASSWORD to the repository secrets, containing the Docker-Hub login.

Multiarch workflows

---

base/Dockerfile

Added `findmnt` #95  and `mongodb-tools` #94 as per issues raised and bumped borgmatic to 1.5.23

Develop > Main

---

base/Dockerfile

Added logrotate package as per #111

Added logrotate package

---

.github/workflows/build_latest.yml
.github/workflows/build_new_version.yml

I've not tested this as with GitHub Actions it's a little chicken and egg. I think the changes are fit for purpose. I would like to deprecate the DockerHub image in the future and this is the first step.

Dual image registry pushing | DockerHub & GHCR

---

base/Dockerfile
base/entry.sh

Recreating https://github.com/borgmatic-collective/docker-borgmatic/pull/142 as discussed. 
@grantbevis @toastie89

Optimise dockerfile

---

README.md
base/Dockerfile
base/entry.sh
base/requirements.txt

This PR covers the changes needed to build our own supercronic binary and the changes to entry.sh

Supercronic

---

IMAGE_ARCHITECTURE.md
README.md
base/README.md
base/docker-compose.yml
msmtp/Dockerfile
msmtp/docker-compose.yml
ntfy/Dockerfile
ntfy/docker-compose.yml

This commit completes the rename across all README, Dockerfiles and docker-compose.ymls.
Signed-off-by: Felix Kaechele <felix@kaechele.ca>
---
I did not touch any of the `LABEL maintainer='b3vis'` lines in the Dockerfiles as I felt that was not for me to decide.

Complete rename

---

base/Dockerfile
base/entry.sh

This resolves https://github.com/borgmatic-collective/docker-borgmatic/issues/203

Add ability to set $SUPERCRONIC_EXTRA_FLAGS

---

base/Dockerfile
base/requirements.txt

Ugrade borgmatic to 1.7.8 and stop compiling `supercronic`

Update to borgmatic 1.7.8

---

Dockerfile

Update docker base image to solve DNS issue https://gitlab.alpinelinux.org/alpine/tsc/-/issues/43

update alpine to 3.18

---

root/etc/s6-overlay/s6-rc.d/svc-cron/run

This resolves issues with printf syntax which doesn't play well with % symbols

change printf to echo

---

.env.template
README.md
docker-compose.restore.yml
docker-compose.yml
root/etc/s6-overlay/s6-rc.d/secrets/finish
root/etc/s6-overlay/s6-rc.d/secrets/run
root/etc/s6-overlay/s6-rc.d/secrets/type
root/etc/s6-overlay/s6-rc.d/secrets/up
root/etc/s6-overlay/s6-rc.d/svc-cron/run

During the extensive changes with the S6 PullRequest #303, we have already discussed that the functionality of the Secrets should be retained, but that we would like to separate them cleanly in the end, when we have dealt with S6 a little more.
After @modem7 drew my attention to another project (https://github.com/linuxserver/docker-baseimage-alpine/blob/master/root/etc/s6-overlay/s6-rc.d/init-envfile/run) and I had a look at the changes made by @chrisblech - I decided to try to separate the cron and the secrets cleanly.
- https://github.com/linuxserver/docker-baseimage-alpine/blob/master/root/etc/s6-overlay/s6-rc.d/init-envfile/run
- https://github.com/caronc/apprise/wiki/Notify_email
There are several points to check with this PullRequest.
Here is an example docker-compose.yml template …

Patch: Separation of secrets and cron

---

README.md

solves https://github.com/borgmatic-collective/docker-borgmatic/issues/376

Update README.md for achieve name gotcha

---

Dockerfile

And update libacl to acl-libs as that was renamed in https://gitlab.alpinelinux.org/alpine/aports/-/commit/0824e5bc4c0d1fb9aac2f133a4c0a92f1f0bb5b4.
Resolves #370.
I haven't tested this apart from to ensure the image builds.

Update to Alpine 3.21 & Postgres 17

---

Dockerfile

Add btrfs-progs to container image

---

root/etc/s6-overlay/s6-rc.d/svc-cron/run

Reverts borgmatic-collective/docker-borgmatic#397

Revert "Update cron configuration logic for corner case"

---

Dockerfile

Update base to use python:3.13.1-alpine3.21

---

Dockerfile

Remove healthcheck
