- Dockerfile
- README.md
- crontab.txt
Borgmatic allows mutliple configuration files:
https://github.com/witten/borgmatic#multiple-configuration-files
Removed `-c` parameter and added a volume for `/etc/borgmatic.d` to store the configuration instead.
Borgmatic searches by default for configuration files in this directory.
> Allow multiple borgmatic configuration files

- README.md
- crontab.txt
Borgmatic writes basically each file to standard out with verbosity = 1, therefore reduced to 0 (warn). In the past I don't remember seeing so many logs, so I suspect [this](https://github.com/witten/borgmatic/commit/7252b8d614456fa509453eca543190203b002528) change causing the the load.
> Changed verbosity to warn

- Dockerfile
Latest Version of Borgmatic:
- with Version 1.2.16 the --extract parameter has been added
> Updated Borgmatic Version to 1.3.0

- .env.template
- .gitignore
- README.md
- data/borgmatic.d/config.yaml
- docker-compose.yml
Moved all config parameter used in  docker-compose.yml to .env and did some minor fixes in README and .gitignore found during testing. This way setting borgmatic using docker-compose will require touching only .env file.
> Full utilization of .env

- .env.template
- Dockerfile
- README.md
- data/borgmatic.d/crontab.txt
- data/borgmatic.d/msmtprc.sh
- docker-compose.yml
- entry.sh
Added the simple mail mta [msmtp](https://wiki.alpinelinux.org/wiki/Relay_email_to_gmail_(msmtp,_mailx,_sendmail ) to send crontab output via mail.
My idea was to get mail in case borgmatic is failing for some reason.
In case you want to change anything comment my pull request and I change it. Your borgmatic is great but I am just missing the mail feature. Thanks for your great container :)!
> Add simple mta for relaying crontab output

- Dockerfile
- README.md
- docker-compose.yml
See #37 for more info.
Testing done: Built a Docker image with these changes, and ran it on an existing servers with two PostgreSQL 11.5 databases. I configured Borgmatic as follows:
```
hooks:
postgresql_databases:
- name: gitea
hostname: gitea-database
username: gitea
password: redacted
- name: mediagoblin
hostname: mediagoblin-database
username: mediagoblin
password: redacted
```
Then I exec'd into the running Docker images and invoked backups manually, confirming that the dump files end up in the expected place in the created archive:
```
...
A /root/.borgmatic/postgresql_databases/mediagoblin-database/mediagoblin                                                                         
A /root/.borgmatic/postgresql_databases/gitea-database/gitea   
...
```
Also confirmed the same …
> Add PostgreSQL client to support database dump hooks (#37).

- .env.template
Added the in PR #38 introduced VOLUME_DOT_BORGMATIC to the .env template as well to be consistent with README.md
> Added VOLUME_DOT_BORGMATIC to template

- Dockerfile
Borgmatic has received numerous bug fixes and improvements since 1.4.0, among others the ability to backup MySQL databases and improved monitoring.
> Upgrade borgmatic to 1.4.21

- README.md
- data/borgmatic.d/crontab.txt
The MAILTO="" in crontab  suppresses output in the docker logs.
> Fixed regression that logs no longer work

- base/Dockerfile
* Update borg to 1.1.13 and borgmatic to 1.5.8
* Replace deprecated `MAINTAINER` to recommended `LABEL maintainer=`
* Fix missing py3-pip package in builder (https://github.com/b3vis/docker-borgmatic/issues/51)
> Update borg to 1.1.13 and borgmatic to 1.5.8

- msmtp/README.md
- msmtp/data/borgmatic.d/crontab.txt
- msmtp/msmtp.env.template
Please double-check this, as I don't want to break anything.
That being said, I think this is redundant as MAILTO must be set in crontab anyway. 
Changing this MAILTO had no effect on the mail recipients and email notifications worked if I removed MAILTO from the container environment variables completely.
> Remove redundant MAILTO from msmtp.env.template

- base/Dockerfile
- ntfy/Dockerfile
fix alpine:3.13 - latest version has python3.9 which this repo is not ready for
fix LLFUSE_VERSION=1.3.8 - llfuse does not build with latest alpine image
> Fix build error

- IMAGE_ARCHITECTURE.md
- msmtp/README.md
- msmtp/data/borgmatic.d/crontab.txt
- msmtp/data/borgmatic.d/env.sh
- msmtp/data/borgmatic.d/msmtprc.sh
- msmtp/data/borgmatic.d/run.sh
- msmtp/entry.sh
- msmtp/msmtp.env.template
The main goal of this PR is to enhance the subject line of e-mail notifications. Currently the subject of the e-mails look like this (created by cron):
```
cron: PATH=$PATH:/usr/bin /usr/bin/borgmatic --stats -v 2 2>&1
```
With this PR, they look like this:
```
✅ SUCCESS: Borgmatic Example Backup
```
```
❌ FAILED: Borgmatic Example Backup
```
I think it's quite obvious that this makes it much easier to see if there are problems as the subject line reflects the backup return status. Especially if you have multiple notifications from different sources in your mailbox.
Apart from this it is now possible to specify the recipients of the notifications in the docker environment.
What I don't really like is the current "abuse" of the `/etc/borgmatic.d` directory for all kinds of other files. …
> Mail subject and env enhancements

- ntfy/README.md
fixes error in parsing configuration file: `At 'hooks.after_backup[1]': {'ntfy -b pushover -t Borgmatic send "Borgmatic': 'Backup Finished"'} is not of type 'string'`
> fix ntfy example

- base/Dockerfile
* #381: BREAKING: Greatly simplify configuration file reuse by deep merging when including common
configuration. See the documentation for more information:
https://torsion.org/borgmatic/docs/how-to/make-per-application-backups/#include-merging
* #473: BREAKING: Instead of executing "before" command hooks before all borgmatic actions run (and
"after" hooks after), execute these hooks right before/after the corresponding action. E.g.,
"before_check" now runs immediately before the "check" action. This better supports running
timing-sensitive tasks like pausing containers. Side effect: before/after command hooks now run
once for each configured repository instead of once per configuration file. Additionally, the
"repositories" interpolated variable has been changed to "repository", …
> Upgrade to borgmatic 1.6.0

- base/Dockerfile
- base/docker-compose.yml
- msmtp/docker-compose.yml
- ntfy/docker-compose.yml
In borgmatic 1.6.2, there will be a new feature for configuring check frequency that will rely on saving state in `~/.borgmatic`. (See https://projects.torsion.org/borgmatic-collective/borgmatic/issues/523 for the gory details.)
This PR is therefore an update to the Docker volumes in this project's container, adding back `/root/.borgmatic` as a volume so that borgmatic's saved state is persisted across container runs. Without this change, borgmatic would "forget" that it had done particular consistency checks and run them more frequently than is configured—not the worst thing in the world, but not ideal.
Testing done: None! (Please let me know if you'd like me to do something in particular.)
> Add borgmatic state volume in preparation for borgmatic 1.6.2 feature

- base/Dockerfile
- base/README.md
borgmatic 1.6.2 will include support for Bash completion (tab completion), and this PR adds support for it to the Docker image. The idea is that you can `exec` into the image (e.g. when viewing or recovering files) and tab-complete your borgmatic command-line.
It's possible that you think Bash doesn't belong in this Docker image. If that's the case, please just let me know and I'll withdraw the PR! But I wanted to send this over in case you wanted it.
NOTE: Please do not land this until after borgmatic 1.6.2 is released! It won't work until then.
Testing done: Built the image (with my local requirements.txt hacked to install borgmatic from master) and ran `docker exec -it borgmatic bash`. Then I started typing `borgmatic ` and hit tab twice to confirm completion worked as expected.
> Bash completion

- msmtp/Dockerfile
- msmtp/data/borgmatic.d/crontab.txt
Hello,
As part of my previous pull request (#133), I forgot to make script files executables right from the Dockerfile. `run.sh` would not run from `crontab.txt` without this modification.
Yann
> Make script files executable

- msmtp/README.md
- Removes migration instructions that are redundant due to the *.sh scripts being moved out of `borgmatic.d` and into `scripts`.
- Added links to `msmtp.env` file and adjusted formatting slightly for consistency.
> Remove redundant msmtp migration instructions

- base/Dockerfile
As we're creating wheels in an index, and not building inside the image, there's no need to have the build step in the Dockerfile. 
I've also changed the image to the python alpine image as we're already installing python 3.10.5, might as well get it directly from the source, and allows for easier updating/rolling back of the core python packages. 
Image build time is reduced, and size is reduced by a few MB.
Have tested with a full backup.
> Optimising Dockerfile

- .github/workflows/build_new_version.yml
the conditional latest tagging was overridden because latest tagging was used in auto mode and triggered by the tagging type=semver,pattern=...
Fixes #151
> disable latest tagging by default

- base/Dockerfile
Added 't' letter to 'mainainer' label in Dockerfile
> Fix a typo in Dockerfile

- base/Dockerfile
Alpine 3.16's included OpenSSL package was 1.1.1. Alpine 3.17 updated it to 3.0.7, which is incompatible with borgbackup. This updates the Dockerfile to pull in the correct library version to avoid this incompatibility.
This resolves https://github.com/borgmatic-collective/docker-borgmatic/issues/180 and https://github.com/borgmatic-collective/docker-borgmatic/issues/184.
> fix: use openssl 1.1 with Alpine 3.17

- base/Dockerfile
- newer MySQL versions have changed the `native_password authentication` to `caching_sha2_password` and therefore the mariadb-connector-c alpine package is required for connectivity, also see [MySQL Manual](https://dev.mysql.com/doc/refman/8.0/en/caching-sha2-pluggable-authentication.html)
Closes #176
> fix(dockerfile): add mariadb-connector-c

- README.md
Updated the docker links for README badges.
preview - https://github.com/diivi/docker-borgmatic/blob/fix/docker-links/README.md
> fix: update README badges

- base/Dockerfile
borgmatic 1.7.9 now supports sqlite db backups, added sqlite client to fix error when trying to backup sqlite files: `/mnt/borg-repository: Error running actions for repository Command 'sqlite3 /mnt/source/mailcow/data/bitwarden/db.sqlite3 .dump > /root/.borgmatic/sqlite_databases/localhost/bitwarden' returned non-zero exit status 127. /etc/borgmatic.d/config.yaml: Error running configuration file`
> add sqlite client

- entry.sh
The echo message says setting to `0 1 * * *` but then actually sets `0 0 * * *`.
> Fix entry.sh default cron schedule

- README.md
fix warning: `generate-borgmatic-config is deprecated and will be removed from a future release. Please use "borgmatic config generate" instead.`
> Update README.md to fix generate-borgmatic-config warning

- README.md
- entry.sh
Related to Ticket #47 and PR #246, a possible implementation of Docker Secrets is provided here. This implementation has been rigorously tested and documented. A key feature is that the use of standard environment variables within Docker commands or `docker-compose.yml` files is preserved. This ensures that those who do not wish to use [Docker Secrets](https://docs.docker.com/compose/use-secrets/) can continue to operate as before.
The function iterates through all environment variables that begin with `BORG`, such as `BORG_PASSPHRASE`. It then looks for variables that end with `_FILE`. The contents of such a `_FILE` variable are written to a new variable, the name of which excludes the `_FILE` suffix. 
> [!NOTE]
> This implementation prioritizes Secrets over regularly set variables. …
> [Feature] Add Docker Secrets support

- README.md
This PR updates the Borgmatic configuration documentation to include Apprise notification support for versions both prior to 1.8.4 and 1.8.4+.
Changes:
- Added section explaining how to set up Apprise notifications in Borgmatic versions before 1.8.4.
- Included a new section that describes the native Apprise configuration in Borgmatic 1.8.4+.
For your convenience, here's a quick preview so you don't have to dig through the documentation:
To enhance your experience with Borgmatic, we'll show you a quick example of how to use Apprise for notifications. Apprise is a versatile tool that integrates with a variety of services and is built into Borgmatic. With the upcoming version 1.8.4 also natively. Here's a quick example of how you can use Apprise.
In an unmodified Borgmatic installation, …
> [Docu] Documentation for Apprise - Supports Pre-1.8.4 and 1.8.4+

- README.md
As part of this PR, I've removed an outdated (and incorrect) method for sending borgmatic's logs to Apprise and called out the new borgmatic 1.8.9 built-in approach.
Also: I haven't done it here, but I might suggest updating the docs to remove the old manual way for sending borgmatic logs to Apprise—or at least swapping the order so the new "native" way comes first. I'd be happy to do this if that's something you're interested in.
> Mention borgmatic 1.8.9+ Apprise log sending capability.

- README.md
This pull request updates `README.md` to add additional instructions for users who are running this container for the first time.
It wasn't immediately obvious to me it was expected to execute into the container to initialize the repo for the first time. This PR adds content to the readme that makes this more apparent.
Thank you!
> Update README.md to include first time details

- data/borgmatic.d/config.yaml
The configuration sections have been deprecated so the hooks should be at root level only.
see #348
> remove duplicated hooks

- README.md
Since Borgmatic v1.9.0, state files for periodic checks are saved at ``/root/.local/state/borgmatic``, the documentation should be updated, as wel as the volume reference in the Dockerfile.
Note: The Dockerfile is another pull Request. I'm new to this... sorry :)
> Update README.md and Dockerfile to reflect new location of statefiles.

- Dockerfile
Since Borgmatic v1.9.0, state files for periodic checks are saved at ``/root/.local/state/borgmatic``, the documentation should be updated, as wel as the volume reference in the Dockerfile.
> Update Dockerfile to reflect new state files path

- root/etc/s6-overlay/s6-rc.d/svc-cron/run
elif Block Not Entering as Expected When BACKUP_CRON Is Unset.
This commit fixes it by setting the flag to '-z' instead of '-v', which allows for unset values to fall in this branch.
Fixes #375
> Update cron configuration logic for corner case

- .github/workflows/build_new_version.yml
- README.md
As described in #351. Seems like an easy change that can add some good functionality. Personally, I want to avoid moving to 2.0 until it's a bit better vetted, so I would use this immediately.
> Added tag that pins to major version
